fix(docker): boltdb support

diff --git a/deployment/docker/common/semaphore-wrapper b/deployment/docker/common/semaphore-wrapper
--- a/deployment/docker/common/semaphore-wrapper
+++ b/deployment/docker/common/semaphore-wrapper
@@ -4,13 +4,13 @@ set -e
 
 echoerr() { printf "%s\n" "$*" >&2; }
 
-SEMAPHORE_CONFIG_PATH="${SEMAPHORE_CONFIG_PATH:-/tmp/semaphore}"
+SEMAPHORE_CONFIG_PATH="${SEMAPHORE_CONFIG_PATH:-/etc/semaphore}"
 SEMAPHORE_TMP_PATH="${SEMAPHORE_TMP_PATH:-/tmp/semaphore}"
 
 # Semaphore database env config
 SEMAPHORE_DB_DIALECT="${SEMAPHORE_DB_DIALECT:-mysql}"
-SEMAPHORE_DB_HOST="${SEMAPHORE_DB_HOST:-127.0.0.1}"
-SEMAPHORE_DB_PATH="${SEMAPHORE_DB_PATH:-/tmp/semaphore/database}"
+SEMAPHORE_DB_HOST="${SEMAPHORE_DB_HOST:-0.0.0.0}"
+SEMAPHORE_DB_PATH="${SEMAPHORE_DB_PATH:-/var/local/semaphore}"
 SEMAPHORE_DB_PORT="${SEMAPHORE_DB_PORT:-}"
 SEMAPHORE_DB="${SEMAPHORE_DB:-semaphore}"
 SEMAPHORE_DB_USER="${SEMAPHORE_DB_USER:-semaphore}"
@@ -38,12 +38,16 @@ SEMAPHORE_LDAP_MAPPING_EMAIL="${SEMAPHORE_LDAP_MAPPING_EMAIL:-mail}"
 
 export SEMAPHORE_ACCESS_KEY_ENCRYPTION="${SEMAPHORE_ACCESS_KEY_ENCRYPTION:-cFcXI5qHzCDqtS4xCnblOACuNu5AmKHkvxK7abwR8Eg=}"
 
-# create semaphore temporary directory if non existent
 [ -d "${SEMAPHORE_TMP_PATH}" ] || mkdir -p "${SEMAPHORE_TMP_PATH}" || {
     echo "Can't create Semaphore tmp path ${SEMAPHORE_TMP_PATH}."
     exit 1
 }
-# create semaphore config directory if non existent
+
+[ -d "${SEMAPHORE_DB_PATH}" ] || mkdir -p "${SEMAPHORE_DB_PATH}" || {
+    echo "Can't create BoltDB path ${SEMAPHORE_DB_PATH}."
+    exit 1
+}
+
 [ -d "${SEMAPHORE_CONFIG_PATH}" ] || mkdir -p "${SEMAPHORE_CONFIG_PATH}" || {
     echo "Can't create Semaphore Config path ${SEMAPHORE_CONFIG_PATH}."
     exit 1
@@ -82,14 +86,16 @@ esac
 # Create a config if it does not exist in the current config path
 if [ ! -f "${SEMAPHORE_CONFIG_PATH}/config.json" ]; then
     echoerr "Generating ${SEMAPHORE_TMP_PATH}/config.stdin ..."
-    if [ "${SEMAPHORE_DB_DIALECT}" = "bolt" ]; then
-      cat << EOF > "${SEMAPHORE_TMP_PATH}/config.stdin"
+    cat << EOF > "${SEMAPHORE_TMP_PATH}/config.stdin"
 ${SEMAPHORE_DB_DIALECT_ID}
+EOF
+
+    if [ "${SEMAPHORE_DB_DIALECT}" = "bolt" ]; then
+      cat << EOF >> "${SEMAPHORE_TMP_PATH}/config.stdin"
 ${SEMAPHORE_DB_PATH}
 EOF
     else
       cat << EOF >> "${SEMAPHORE_TMP_PATH}/config.stdin"
-${SEMAPHORE_DB_DIALECT_ID}
 ${SEMAPHORE_DB_HOST}
 ${SEMAPHORE_DB_USER}
 ${SEMAPHORE_DB_PASS}
