Rename

diff --git a/deployment/docker/server/server-wrapper b/deployment/docker/server/server-wrapper
--- a/deployment/docker/server/server-wrapper
+++ b/deployment/docker/server/server-wrapper
@@ -34,97 +34,97 @@ file_env() {
     unset "${1}_FILE"
 }
 
-export SEMAPHORE_CONFIG_PATH="${SEMAPHORE_CONFIG_PATH:-/etc/forge}"
-export SEMAPHORE_DB_PATH="${SEMAPHORE_DB_PATH:-/var/lib/forge}"
-export SEMAPHORE_DB_PORT="${SEMAPHORE_DB_PORT:-}"
+export FORGE_CONFIG_PATH="${FORGE_CONFIG_PATH:-/etc/forge}"
+export FORGE_DB_PATH="${FORGE_DB_PATH:-/var/lib/forge}"
+export FORGE_DB_PORT="${FORGE_DB_PORT:-}"
 
-file_env 'SEMAPHORE_DB_USER'
-file_env 'SEMAPHORE_DB_PASS'
-file_env 'SEMAPHORE_ADMIN'
-export SEMAPHORE_ADMIN_EMAIL="${SEMAPHORE_ADMIN_EMAIL:-admin@localhost}"
-export SEMAPHORE_ADMIN_NAME="${SEMAPHORE_ADMIN_NAME:-Semaphore Admin}"
-file_env 'SEMAPHORE_ADMIN_PASSWORD'
-export SEMAPHORE_LDAP_ACTIVATED="${SEMAPHORE_LDAP_ACTIVATED:-no}"
-export SEMAPHORE_LDAP_HOST="${SEMAPHORE_LDAP_HOST:-}"
-export SEMAPHORE_LDAP_PORT="${SEMAPHORE_LDAP_PORT:-}"
-export SEMAPHORE_LDAP_DN_BIND="${SEMAPHORE_LDAP_DN_BIND:-}"
-file_env 'SEMAPHORE_LDAP_PASSWORD'
-export SEMAPHORE_LDAP_DN_SEARCH="${SEMAPHORE_LDAP_DN_SEARCH:-}"
-export SEMAPHORE_LDAP_MAPPING_USERNAME="${SEMAPHORE_LDAP_MAPPING_USERNAME:-uid}"
-export SEMAPHORE_LDAP_MAPPING_FULLNAME="${SEMAPHORE_LDAP_MAPPING_FULLNAME:-cn}"
-export SEMAPHORE_LDAP_MAPPING_EMAIL="${SEMAPHORE_LDAP_MAPPING_EMAIL:-mail}"
-file_env 'SEMAPHORE_ACCESS_KEY_ENCRYPTION'
+file_env 'FORGE_DB_USER'
+file_env 'FORGE_DB_PASS'
+file_env 'FORGE_ADMIN'
+export FORGE_ADMIN_EMAIL="${FORGE_ADMIN_EMAIL:-admin@localhost}"
+export FORGE_ADMIN_NAME="${FORGE_ADMIN_NAME:-Semaphore Admin}"
+file_env 'FORGE_ADMIN_PASSWORD'
+export FORGE_LDAP_ACTIVATED="${FORGE_LDAP_ACTIVATED:-no}"
+export FORGE_LDAP_HOST="${FORGE_LDAP_HOST:-}"
+export FORGE_LDAP_PORT="${FORGE_LDAP_PORT:-}"
+export FORGE_LDAP_DN_BIND="${FORGE_LDAP_DN_BIND:-}"
+file_env 'FORGE_LDAP_PASSWORD'
+export FORGE_LDAP_DN_SEARCH="${FORGE_LDAP_DN_SEARCH:-}"
+export FORGE_LDAP_MAPPING_USERNAME="${FORGE_LDAP_MAPPING_USERNAME:-uid}"
+export FORGE_LDAP_MAPPING_FULLNAME="${FORGE_LDAP_MAPPING_FULLNAME:-cn}"
+export FORGE_LDAP_MAPPING_EMAIL="${FORGE_LDAP_MAPPING_EMAIL:-mail}"
+file_env 'FORGE_ACCESS_KEY_ENCRYPTION'
 
 
-[ -d "${SEMAPHORE_CONFIG_PATH}" ] || mkdir -p "${SEMAPHORE_CONFIG_PATH}" || {
-    echo "Can't create Semaphore config path ${SEMAPHORE_CONFIG_PATH}."
+[ -d "${FORGE_CONFIG_PATH}" ] || mkdir -p "${FORGE_CONFIG_PATH}" || {
+    echo "Can't create Semaphore config path ${FORGE_CONFIG_PATH}."
     exit 1
 }
 
-[ -d "${SEMAPHORE_DB_PATH}" ] || mkdir -p "${SEMAPHORE_DB_PATH}" || {
-    echo "Can't create Semaphore data path ${SEMAPHORE_DB_PATH}."
+[ -d "${FORGE_DB_PATH}" ] || mkdir -p "${FORGE_DB_PATH}" || {
+    echo "Can't create Semaphore data path ${FORGE_DB_PATH}."
     exit 1
 }
 
 
 #
 # Extract database host and port from config.json if they are not set.
-# Set default SEMAPHORE_DB_DIALECT and SEMAPHORE_DB_HOST if empty.
+# Set default FORGE_DB_DIALECT and FORGE_DB_HOST if empty.
 #
-if [ -z "${SEMAPHORE_DB_DIALECT}" ]; then
-    if [ -f "${SEMAPHORE_CONFIG_PATH}/config.json" ]; then
-        SEMAPHORE_DB_DIALECT=$(cat "${SEMAPHORE_CONFIG_PATH}/config.json" | jq '.dialect // ""' -r)
+if [ -z "${FORGE_DB_DIALECT}" ]; then
+    if [ -f "${FORGE_CONFIG_PATH}/config.json" ]; then
+        FORGE_DB_DIALECT=$(cat "${FORGE_CONFIG_PATH}/config.json" | jq '.dialect // ""' -r)
     fi
 fi
 
-export SEMAPHORE_DB_DIALECT="${SEMAPHORE_DB_DIALECT:-mysql}"
+export FORGE_DB_DIALECT="${FORGE_DB_DIALECT:-mysql}"
 
-if [ -z "${SEMAPHORE_DB_HOST}" ]; then
-    if [ -f "${SEMAPHORE_CONFIG_PATH}/config.json" ]; then
-        SEMAPHORE_DB_HOST=$(cat "${SEMAPHORE_CONFIG_PATH}/config.json" | jq ".${SEMAPHORE_DB_DIALECT}.host // \"\"" -r)
+if [ -z "${FORGE_DB_HOST}" ]; then
+    if [ -f "${FORGE_CONFIG_PATH}/config.json" ]; then
+        FORGE_DB_HOST=$(cat "${FORGE_CONFIG_PATH}/config.json" | jq ".${FORGE_DB_DIALECT}.host // \"\"" -r)
     fi
 fi
 
-if [ -z "${SEMAPHORE_DB_HOST}" ]; then
-    if [ "${SEMAPHORE_DB_DIALECT}" = 'bolt' ]; then
-        export SEMAPHORE_DB_HOST=${SEMAPHORE_DB_PATH}/database.boltdb
-    elif [ "${SEMAPHORE_DB_DIALECT}" = 'sqlite' ]; then
-        export SEMAPHORE_DB_HOST=${SEMAPHORE_DB_PATH}/database.sqlite
+if [ -z "${FORGE_DB_HOST}" ]; then
+    if [ "${FORGE_DB_DIALECT}" = 'bolt' ]; then
+        export FORGE_DB_HOST=${FORGE_DB_PATH}/database.boltdb
+    elif [ "${FORGE_DB_DIALECT}" = 'sqlite' ]; then
+        export FORGE_DB_HOST=${FORGE_DB_PATH}/database.sqlite
     else
-        export SEMAPHORE_DB_HOST="${SEMAPHORE_DB_HOST:-0.0.0.0}"
+        export FORGE_DB_HOST="${FORGE_DB_HOST:-0.0.0.0}"
     fi
 fi
 
 
 #
-# Remove port number from SEMAPHORE_DB_HOST and put it to SEMAPHORE_DB_PORT
+# Remove port number from FORGE_DB_HOST and put it to FORGE_DB_PORT
 #
-case "$SEMAPHORE_DB_HOST" in
+case "$FORGE_DB_HOST" in
   *:*)
-    SEMAPHORE_DB_PORT=$(echo "$SEMAPHORE_DB_HOST" | cut -d ':' -f 2)
-    SEMAPHORE_DB_HOST=$(echo "$SEMAPHORE_DB_HOST" | cut -d ':' -f 1)
+    FORGE_DB_PORT=$(echo "$FORGE_DB_HOST" | cut -d ':' -f 2)
+    FORGE_DB_HOST=$(echo "$FORGE_DB_HOST" | cut -d ':' -f 1)
     ;;
   *)
 esac
 
 
 #
-# Set SEMAPHORE_DB_PORT if it is not set
+# Set FORGE_DB_PORT if it is not set
 #
-if [ -z "${SEMAPHORE_DB_PORT}" ]; then
-    case ${SEMAPHORE_DB_DIALECT} in
+if [ -z "${FORGE_DB_PORT}" ]; then
+    case ${FORGE_DB_DIALECT} in
         mysql)
-            SEMAPHORE_DB_PORT=3306
+            FORGE_DB_PORT=3306
             ;;
         postgres)
-            SEMAPHORE_DB_PORT=5432
+            FORGE_DB_PORT=5432
             ;;
         bolt)
             ;;
         sqlite)
             ;;
         *)
-            echoerr "Unknown database dialect: ${SEMAPHORE_DB_DIALECT}"
+            echoerr "Unknown database dialect: ${FORGE_DB_DIALECT}"
             exit 1
             ;;
     esac
@@ -134,12 +134,12 @@ fi
 #
 # Ping database if it is not BoltDB
 #
-if [ "${SEMAPHORE_DB_DIALECT}" != 'bolt' ] && [ "${SEMAPHORE_DB_DIALECT}" != 'sqlite' ]; then
-    echoerr "Pinging database on ${SEMAPHORE_DB_HOST} port ${SEMAPHORE_DB_PORT}..."
+if [ "${FORGE_DB_DIALECT}" != 'bolt' ] && [ "${FORGE_DB_DIALECT}" != 'sqlite' ]; then
+    echoerr "Pinging database on ${FORGE_DB_HOST} port ${FORGE_DB_PORT}..."
     TIMEOUT=30
 
 
-    while ! $(nc -z "$SEMAPHORE_DB_HOST" "$SEMAPHORE_DB_PORT") >/dev/null 2>&1; do
+    while ! $(nc -z "$FORGE_DB_HOST" "$FORGE_DB_PORT") >/dev/null 2>&1; do
         TIMEOUT=$(expr $TIMEOUT - 1)
 
         if [ $TIMEOUT -eq 0 ]; then
@@ -151,99 +151,99 @@ if [ "${SEMAPHORE_DB_DIALECT}" != 'bolt' ] && [ "${SEMAPHORE_DB_DIALECT}" != 'sq
         sleep 1
     done
     
-    export SEMAPHORE_DB_HOST="${SEMAPHORE_DB_HOST}:${SEMAPHORE_DB_PORT}"
+    export FORGE_DB_HOST="${FORGE_DB_HOST}:${FORGE_DB_PORT}"
 fi
 
 
 #
 # Generate new config.json if it does not exist
 #
-if [ ! -f "${SEMAPHORE_CONFIG_PATH}/config.json" ]; then
+if [ ! -f "${FORGE_CONFIG_PATH}/config.json" ]; then
     echoerr "Generating setup file ${TMP_STDIN_CONFIG_FILE} ..."
 
     TMP_STDIN_CONFIG_FILE=$(mktemp)
 
 
-    SEMAPHORE_TMP_PATH=${SEMAPHORE_TMP_PATH:-/tmp/forge}
-    [ -d "${SEMAPHORE_TMP_PATH}" ] || mkdir -p "${SEMAPHORE_TMP_PATH}" || {
-        echo "Can't create Semaphore tmp path ${SEMAPHORE_TMP_PATH}."
+    FORGE_TMP_PATH=${FORGE_TMP_PATH:-/tmp/forge}
+    [ -d "${FORGE_TMP_PATH}" ] || mkdir -p "${FORGE_TMP_PATH}" || {
+        echo "Can't create Semaphore tmp path ${FORGE_TMP_PATH}."
         exit 1
     }
 
 
-    case ${SEMAPHORE_DB_DIALECT} in
+    case ${FORGE_DB_DIALECT} in
         mysql)
-            SEMAPHORE_DB_DIALECT_ID=1
+            FORGE_DB_DIALECT_ID=1
             ;;
         bolt)
-            SEMAPHORE_DB_DIALECT_ID=2
+            FORGE_DB_DIALECT_ID=2
             ;;
         postgres)
-            SEMAPHORE_DB_DIALECT_ID=3
+            FORGE_DB_DIALECT_ID=3
             ;;
         sqlite)
-            SEMAPHORE_DB_DIALECT_ID=4
+            FORGE_DB_DIALECT_ID=4
             ;;
         *)
-            echoerr "Unknown database dialect: ${SEMAPHORE_DB_DIALECT}"
+            echoerr "Unknown database dialect: ${FORGE_DB_DIALECT}"
             exit 1
             ;;
     esac
 
 
     cat << EOF > "${TMP_STDIN_CONFIG_FILE}"
-${SEMAPHORE_DB_DIALECT_ID}
+${FORGE_DB_DIALECT_ID}
 EOF
 
-    if [ "${SEMAPHORE_DB_DIALECT}" = "bolt" ]; then
+    if [ "${FORGE_DB_DIALECT}" = "bolt" ]; then
         cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
-${SEMAPHORE_DB_HOST}
+${FORGE_DB_HOST}
 EOF
-    elif [ "${SEMAPHORE_DB_DIALECT}" = "sqlite" ]; then
+    elif [ "${FORGE_DB_DIALECT}" = "sqlite" ]; then
         cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
-${SEMAPHORE_DB_HOST}
+${FORGE_DB_HOST}
 EOF
     else
         cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
-${SEMAPHORE_DB_HOST}
-${SEMAPHORE_DB_USER}
-${SEMAPHORE_DB_PASS}
-${SEMAPHORE_DB:-forge}
+${FORGE_DB_HOST}
+${FORGE_DB_USER}
+${FORGE_DB_PASS}
+${FORGE_DB:-forge}
 EOF
     fi
 
     cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
-${SEMAPHORE_TMP_PATH}
-${SEMAPHORE_WEB_ROOT:-}
+${FORGE_TMP_PATH}
+${FORGE_WEB_ROOT:-}
 no
 no
 no
 no
 no
-${SEMAPHORE_LDAP_ACTIVATED}
+${FORGE_LDAP_ACTIVATED}
 EOF
 
-    if [ "${SEMAPHORE_LDAP_ACTIVATED}" = "yes" ]; then
+    if [ "${FORGE_LDAP_ACTIVATED}" = "yes" ]; then
         cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
-${SEMAPHORE_LDAP_HOST}:${SEMAPHORE_LDAP_PORT}
-${SEMAPHORE_LDAP_NEEDTLS:-no}
-${SEMAPHORE_LDAP_DN_BIND}
-${SEMAPHORE_LDAP_PASSWORD}
-${SEMAPHORE_LDAP_DN_SEARCH}
-${SEMAPHORE_LDAP_SEARCH_FILTER:-(uid=%s)}
-${SEMAPHORE_LDAP_MAPPING_DN:-dn}
-${SEMAPHORE_LDAP_MAPPING_USERNAME}
-${SEMAPHORE_LDAP_MAPPING_FULLNAME}
-${SEMAPHORE_LDAP_MAPPING_EMAIL}
+${FORGE_LDAP_HOST}:${FORGE_LDAP_PORT}
+${FORGE_LDAP_NEEDTLS:-no}
+${FORGE_LDAP_DN_BIND}
+${FORGE_LDAP_PASSWORD}
+${FORGE_LDAP_DN_SEARCH}
+${FORGE_LDAP_SEARCH_FILTER:-(uid=%s)}
+${FORGE_LDAP_MAPPING_DN:-dn}
+${FORGE_LDAP_MAPPING_USERNAME}
+${FORGE_LDAP_MAPPING_FULLNAME}
+${FORGE_LDAP_MAPPING_EMAIL}
 EOF
     fi;
 
     cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
-${SEMAPHORE_CONFIG_PATH}
-${SEMAPHORE_ADMIN}
-${SEMAPHORE_ADMIN_EMAIL}
-${SEMAPHORE_ADMIN_NAME}
-${SEMAPHORE_ADMIN_PASSWORD}
+${FORGE_CONFIG_PATH}
+${FORGE_ADMIN}
+${FORGE_ADMIN_EMAIL}
+${FORGE_ADMIN_NAME}
+${FORGE_ADMIN_PASSWORD}
 EOF
 
 
@@ -261,10 +261,10 @@ fi
 #
 # Install additional python dependencies
 #
-if test -f "${SEMAPHORE_CONFIG_PATH}/requirements.txt"; then
+if test -f "${FORGE_CONFIG_PATH}/requirements.txt"; then
     echoerr "Installing additional python dependencies"
     pip3 install --upgrade \
-        -r "${SEMAPHORE_CONFIG_PATH}/requirements.txt"
+        -r "${FORGE_CONFIG_PATH}/requirements.txt"
 else
     echoerr "No additional python dependencies to install"
 fi
@@ -275,7 +275,7 @@ fi
 #
 echoerr "Starting forge server"
 if test "$#" -ne 1; then
-    exec /usr/local/bin/forge server  --config "${SEMAPHORE_CONFIG_PATH}/config.json"
+    exec /usr/local/bin/forge server  --config "${FORGE_CONFIG_PATH}/config.json"
 else
     exec "$@"
 fi
