ci(wrapper): remove extra veriables

diff --git a/deployment/docker/server/server-wrapper b/deployment/docker/server/server-wrapper
--- a/deployment/docker/server/server-wrapper
+++ b/deployment/docker/server/server-wrapper
@@ -32,12 +32,10 @@ file_env() {
 }
 
 export SEMAPHORE_CONFIG_PATH="${SEMAPHORE_CONFIG_PATH:-/etc/semaphore}"
-export SEMAPHORE_TMP_PATH="${SEMAPHORE_TMP_PATH:-/tmp/semaphore}"
-export SEMAPHORE_DB_DIALECT="${SEMAPHORE_DB_DIALECT:-mysql}"
-export SEMAPHORE_DB_HOST="${SEMAPHORE_DB_HOST:-0.0.0.0}"
+export SEMAPHORE_DB_DIALECT="${SEMAPHORE_DB_DIALECT:-mysql}" # duplicate
+export SEMAPHORE_DB_HOST="${SEMAPHORE_DB_HOST:-0.0.0.0}" # duplicate
 export SEMAPHORE_DB_PATH="${SEMAPHORE_DB_PATH:-/var/lib/semaphore}"
 export SEMAPHORE_DB_PORT="${SEMAPHORE_DB_PORT:-}"
-export SEMAPHORE_DB="${SEMAPHORE_DB:-semaphore}"
 
 file_env 'SEMAPHORE_DB_USER' 'semaphore'
 file_env 'SEMAPHORE_DB_PASS' 'semaphore'
@@ -56,10 +54,6 @@ export SEMAPHORE_LDAP_MAPPING_FULLNAME="${SEMAPHORE_LDAP_MAPPING_FULLNAME:-cn}"
 export SEMAPHORE_LDAP_MAPPING_EMAIL="${SEMAPHORE_LDAP_MAPPING_EMAIL:-mail}"
 file_env 'SEMAPHORE_ACCESS_KEY_ENCRYPTION'
 
-[ -d "${SEMAPHORE_TMP_PATH}" ] || mkdir -p "${SEMAPHORE_TMP_PATH}" || {
-    echo "Can't create Semaphore tmp path ${SEMAPHORE_TMP_PATH}."
-    exit 1
-}
 
 [ -d "${SEMAPHORE_CONFIG_PATH}" ] || mkdir -p "${SEMAPHORE_CONFIG_PATH}" || {
     echo "Can't create Semaphore config path ${SEMAPHORE_CONFIG_PATH}."
@@ -71,7 +65,10 @@ file_env 'SEMAPHORE_ACCESS_KEY_ENCRYPTION'
     exit 1
 }
 
-# Check if $SEMAPHORE_DB_HOST contains port number.
+
+#
+# Remove port number from SEMAPHORE_DB_HOST and put it to SEMAPHORE_DB_PORT
+#
 case "$SEMAPHORE_DB_HOST" in
   *:*)
     SEMAPHORE_DB_PORT=$(echo "$SEMAPHORE_DB_HOST" | cut -d ':' -f 2)
@@ -80,6 +77,10 @@ case "$SEMAPHORE_DB_HOST" in
   *)
 esac
 
+
+#
+# Set SEMAPHORE_DB_PORT if it is not set
+#
 if [ -z "${SEMAPHORE_DB_PORT}" ]; then
     case ${SEMAPHORE_DB_DIALECT} in
         mysql)
@@ -97,9 +98,12 @@ if [ -z "${SEMAPHORE_DB_PORT}" ]; then
     esac
 fi
 
+
+#
 # Ping database if it is not BoltDB
+#
 if [ "${SEMAPHORE_DB_DIALECT}" != 'bolt' ]; then
-    echoerr "Attempting to connect to database ${SEMAPHORE_DB} on ${SEMAPHORE_DB_HOST}:${SEMAPHORE_DB_PORT} with user ${SEMAPHORE_DB_USER} ..."
+    echoerr "Ping database on ${SEMAPHORE_DB_HOST}:${SEMAPHORE_DB_PORT} with user ${SEMAPHORE_DB_USER} ..."
     TIMEOUT=30
 
 
@@ -137,26 +141,40 @@ case ${SEMAPHORE_DB_DIALECT} in
         ;;
 esac
 
+
+
+#
+# Generate new config.json if it does not exist
+#
 if [ ! -f "${SEMAPHORE_CONFIG_PATH}/config.json" ]; then
-    echoerr "Generating ${SEMAPHORE_TMP_PATH}/config.stdin ..."
-    cat << EOF > "${SEMAPHORE_TMP_PATH}/config.stdin"
+    echoerr "Generating setup file ${TMP_STDIN_CONFIG_FILE} ..."
+
+    TMP_STDIN_CONFIG_FILE=$(mktemp)
+
+    SEMAPHORE_TMP_PATH=${SEMAPHORE_TMP_PATH:-/tmp/semaphore}
+    [ -d "${SEMAPHORE_TMP_PATH}" ] || mkdir -p "${SEMAPHORE_TMP_PATH}" || {
+        echo "Can't create Semaphore tmp path ${SEMAPHORE_TMP_PATH}."
+        exit 1
+    }
+
+    cat << EOF > "${TMP_STDIN_CONFIG_FILE}"
 ${SEMAPHORE_DB_DIALECT_ID}
 EOF
 
     if [ "${SEMAPHORE_DB_DIALECT}" = "bolt" ]; then
-        cat << EOF >> "${SEMAPHORE_TMP_PATH}/config.stdin"
+        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
 ${SEMAPHORE_DB_HOST}
 EOF
     else
-        cat << EOF >> "${SEMAPHORE_TMP_PATH}/config.stdin"
+        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
 ${SEMAPHORE_DB_HOST}:${SEMAPHORE_DB_PORT}
 ${SEMAPHORE_DB_USER}
 ${SEMAPHORE_DB_PASS}
-${SEMAPHORE_DB}
+${SEMAPHORE_DB:-semaphore}
 EOF
     fi
 
-    cat << EOF >> "${SEMAPHORE_TMP_PATH}/config.stdin"
+    cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
 ${SEMAPHORE_TMP_PATH}
 ${SEMAPHORE_WEB_ROOT:-}
 no
@@ -168,7 +186,7 @@ ${SEMAPHORE_LDAP_ACTIVATED}
 EOF
 
     if [ "${SEMAPHORE_LDAP_ACTIVATED}" = "yes" ]; then
-        cat << EOF >> "${SEMAPHORE_TMP_PATH}/config.stdin"
+        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
 ${SEMAPHORE_LDAP_HOST}:${SEMAPHORE_LDAP_PORT}
 ${SEMAPHORE_LDAP_NEEDTLS:-no}
 ${SEMAPHORE_LDAP_DN_BIND}
@@ -182,7 +200,7 @@ ${SEMAPHORE_LDAP_MAPPING_EMAIL}
 EOF
     fi;
 
-    cat << EOF >> "${SEMAPHORE_TMP_PATH}/config.stdin"
+    cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
 ${SEMAPHORE_CONFIG_PATH}
 ${SEMAPHORE_ADMIN}
 ${SEMAPHORE_ADMIN_EMAIL}
@@ -192,11 +210,12 @@ EOF
 
     echoerr "Executing semaphore setup"
     if test "$#" -ne 1; then
-        /usr/local/bin/semaphore setup - < "${SEMAPHORE_TMP_PATH}/config.stdin"
+        /usr/local/bin/semaphore setup - < "${TMP_STDIN_CONFIG_FILE}"
     else
-        "$1" setup - < "${SEMAPHORE_TMP_PATH}/config.stdin"
+        "$1" setup - < "${TMP_STDIN_CONFIG_FILE}"
     fi
 fi
+
 
 if test -f "${SEMAPHORE_CONFIG_PATH}/packages.txt"; then
     echoerr "Installing additional system dependencies"
@@ -206,6 +225,10 @@ else
     echoerr "No additional system dependencies to install"
 fi
 
+
+#
+# Install additional python dependencies
+#
 if test -f "${SEMAPHORE_CONFIG_PATH}/requirements.txt"; then
     echoerr "Installing additional python dependencies"
     pip3 install --upgrade \
@@ -214,6 +237,10 @@ else
     echoerr "No additional python dependencies to install"
 fi
 
+
+#
+# Start Semaphore server
+#
 echoerr "Starting semaphore server"
 if test "$#" -ne 1; then
     exec /usr/local/bin/semaphore server  --config "${SEMAPHORE_CONFIG_PATH}/config.json"
